apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static
  namespace: netology
  labels:
    app: nginx-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      namespace: netology
      labels:
        app: nginx-static
    spec:
      containers:
        - name: myapp
          image: sergeymeljnick78/myapp:3.01
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-static
  namespace: netology
spec:
  selector:
    app: nginx-static
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31001
  type: NodePort
